# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/ad2039/G00StereoCamera/zcu102_ds.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_intc_0_0/design_1_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_intc_0_0 || ORIG_REF_NAME==design_1_axi_intc_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_hp1_0/design_1_axi_interconnect_hp1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_hp1_0 || ORIG_REF_NAME==design_1_axi_interconnect_hp1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_hpm0_0/design_1_axi_interconnect_hpm0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_hpm0_0 || ORIG_REF_NAME==design_1_axi_interconnect_hpm0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_hpm1_0/design_1_axi_interconnect_hpm1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_hpm1_0 || ORIG_REF_NAME==design_1_axi_interconnect_hpm1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_1_0/design_1_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_1_0 || ORIG_REF_NAME==design_1_clk_wiz_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_interrupts0_0/design_1_interrupts0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_interrupts0_0 || ORIG_REF_NAME==design_1_interrupts0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_platform_interrupts_0/design_1_platform_interrupts_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_platform_interrupts_0 || ORIG_REF_NAME==design_1_platform_interrupts_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sensor0_iic_0/design_1_sensor0_iic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sensor0_iic_0 || ORIG_REF_NAME==design_1_sensor0_iic_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sensor1_iic_0/design_1_sensor1_iic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sensor1_iic_0 || ORIG_REF_NAME==design_1_sensor1_iic_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_data_fifo_0_1/design_1_axi_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_data_fifo_0_1 || ORIG_REF_NAME==design_1_axi_data_fifo_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_0_1/design_1_axis_subset_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_0_1 || ORIG_REF_NAME==design_1_axis_subset_converter_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_demosaic_rst_gpio_1/design_1_demosaic_rst_gpio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_demosaic_rst_gpio_1 || ORIG_REF_NAME==design_1_demosaic_rst_gpio_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_frmbuf_wr_rst_gpio_1/design_1_frmbuf_wr_rst_gpio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_frmbuf_wr_rst_gpio_1 || ORIG_REF_NAME==design_1_frmbuf_wr_rst_gpio_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_gamma_rst_gpio_1/design_1_gamma_rst_gpio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_gamma_rst_gpio_1 || ORIG_REF_NAME==design_1_gamma_rst_gpio_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/design_1_mipi_csi2_rx_subsystem_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mipi_csi2_rx_subsystem_0_1 || ORIG_REF_NAME==design_1_mipi_csi2_rx_subsystem_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sensor_rst_gpio_1/design_1_sensor_rst_gpio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sensor_rst_gpio_1 || ORIG_REF_NAME==design_1_sensor_rst_gpio_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_demosaic_0_1/design_1_v_demosaic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_demosaic_0_1 || ORIG_REF_NAME==design_1_v_demosaic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_frmbuf_wr_0_1/design_1_v_frmbuf_wr_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_wr_0_1 || ORIG_REF_NAME==design_1_v_frmbuf_wr_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_gamma_lut_0_1/design_1_v_gamma_lut_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_gamma_lut_0_1 || ORIG_REF_NAME==design_1_v_gamma_lut_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_proc_ss_csc_1/design_1_v_proc_ss_csc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_proc_ss_csc_1 || ORIG_REF_NAME==design_1_v_proc_ss_csc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_proc_ss_scaler_1/design_1_v_proc_ss_scaler_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_proc_ss_scaler_1 || ORIG_REF_NAME==design_1_v_proc_ss_scaler_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vcc_1/design_1_vcc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vcc_1 || ORIG_REF_NAME==design_1_vcc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vpss_csc_rst_gpio_1/design_1_vpss_csc_rst_gpio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vpss_csc_rst_gpio_1 || ORIG_REF_NAME==design_1_vpss_csc_rst_gpio_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vpss_scaler_rst_gpio_1/design_1_vpss_scaler_rst_gpio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vpss_scaler_rst_gpio_1 || ORIG_REF_NAME==design_1_vpss_scaler_rst_gpio_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_data_fifo_0_0/design_1_axi_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_data_fifo_0_0 || ORIG_REF_NAME==design_1_axi_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_0_0 || ORIG_REF_NAME==design_1_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_demosaic_rst_gpio_0/design_1_demosaic_rst_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_demosaic_rst_gpio_0 || ORIG_REF_NAME==design_1_demosaic_rst_gpio_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_frmbuf_wr_rst_gpio_0/design_1_frmbuf_wr_rst_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_frmbuf_wr_rst_gpio_0 || ORIG_REF_NAME==design_1_frmbuf_wr_rst_gpio_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_gamma_rst_gpio_0/design_1_gamma_rst_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_gamma_rst_gpio_0 || ORIG_REF_NAME==design_1_gamma_rst_gpio_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_mipi_csi2_rx_subsystem_0_0 || ORIG_REF_NAME==design_1_mipi_csi2_rx_subsystem_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_sensor_rst_gpio_0/design_1_sensor_rst_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sensor_rst_gpio_0 || ORIG_REF_NAME==design_1_sensor_rst_gpio_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_demosaic_0_0/design_1_v_demosaic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_demosaic_0_0 || ORIG_REF_NAME==design_1_v_demosaic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_wr_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_wr_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_gamma_lut_0_0/design_1_v_gamma_lut_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_gamma_lut_0_0 || ORIG_REF_NAME==design_1_v_gamma_lut_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_proc_ss_csc_0/design_1_v_proc_ss_csc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_proc_ss_csc_0 || ORIG_REF_NAME==design_1_v_proc_ss_csc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_proc_ss_scaler_0/design_1_v_proc_ss_scaler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_v_proc_ss_scaler_0 || ORIG_REF_NAME==design_1_v_proc_ss_scaler_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vcc_0/design_1_vcc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vcc_0 || ORIG_REF_NAME==design_1_vcc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vpss_csc_rst_gpio_0/design_1_vpss_csc_rst_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vpss_csc_rst_gpio_0 || ORIG_REF_NAME==design_1_vpss_csc_rst_gpio_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vpss_scaler_rst_gpio_0/design_1_vpss_scaler_rst_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vpss_scaler_rst_gpio_0 || ORIG_REF_NAME==design_1_vpss_scaler_rst_gpio_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2/design_1_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_1/design_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_0_0/design_1_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_0_0 || ORIG_REF_NAME==design_1_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_1_0/design_1_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_1_0 || ORIG_REF_NAME==design_1_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_2_0/design_1_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_2_0 || ORIG_REF_NAME==design_1_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m10_regslice_0/design_1_m10_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m10_regslice_0 || ORIG_REF_NAME==design_1_m10_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m09_regslice_0/design_1_m09_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m09_regslice_0 || ORIG_REF_NAME==design_1_m09_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m08_regslice_0/design_1_m08_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m08_regslice_0 || ORIG_REF_NAME==design_1_m08_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m07_regslice_0/design_1_m07_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m07_regslice_0 || ORIG_REF_NAME==design_1_m07_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m06_regslice_0/design_1_m06_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m06_regslice_0 || ORIG_REF_NAME==design_1_m06_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m05_regslice_0/design_1_m05_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m05_regslice_0 || ORIG_REF_NAME==design_1_m05_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m04_regslice_0/design_1_m04_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m04_regslice_0 || ORIG_REF_NAME==design_1_m04_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m03_regslice_0/design_1_m03_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m03_regslice_0 || ORIG_REF_NAME==design_1_m03_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m02_regslice_0/design_1_m02_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m02_regslice_0 || ORIG_REF_NAME==design_1_m02_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m01_regslice_0/design_1_m01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m01_regslice_0 || ORIG_REF_NAME==design_1_m01_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_regslice_1/design_1_m00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_1 || ORIG_REF_NAME==design_1_m00_regslice_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_1/design_1_s00_regslice_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_1 || ORIG_REF_NAME==design_1_s00_regslice_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_mmu_0/design_1_s00_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_mmu_0 || ORIG_REF_NAME==design_1_s00_mmu_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s01_mmu_0/design_1_s01_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s01_mmu_0 || ORIG_REF_NAME==design_1_s01_mmu_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_data_fifo_0/design_1_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m00_data_fifo_0 || ORIG_REF_NAME==design_1_m00_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_regslice_0/design_1_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_0 || ORIG_REF_NAME==design_1_m00_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s01_regslice_0/design_1_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s01_regslice_0 || ORIG_REF_NAME==design_1_s01_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s01_data_fifo_0/design_1_s01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s01_data_fifo_0 || ORIG_REF_NAME==design_1_s01_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_0/design_1_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_0 || ORIG_REF_NAME==design_1_s00_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_data_fifo_0/design_1_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_0 || ORIG_REF_NAME==design_1_s00_data_fifo_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
