# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_sensor1_iic_0/design_1_sensor1_iic_0.xci
# IP: The module: 'design_1_sensor1_iic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_sensor1_iic_0/design_1_sensor1_iic_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sensor1_iic_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_sensor1_iic_0/design_1_sensor1_iic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sensor1_iic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_sensor1_iic_0/design_1_sensor1_iic_0.xci
# IP: The module: 'design_1_sensor1_iic_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_sensor1_iic_0/design_1_sensor1_iic_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sensor1_iic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_sensor1_iic_0/design_1_sensor1_iic_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_sensor1_iic_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
