# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/design_1_v_proc_ss_scaler_0.xci
# IP: The module: 'design_1_v_proc_ss_scaler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/bd_c7bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd || ORIG_REF_NAME==bd_c7bd} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_0/bd_c7bd_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_axi_interconnect_0_0 || ORIG_REF_NAME==bd_c7bd_axi_interconnect_0_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_2/bd_c7bd_vsc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_vsc_0 || ORIG_REF_NAME==bd_c7bd_vsc_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_3/bd_c7bd_hsc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_hsc_0 || ORIG_REF_NAME==bd_c7bd_hsc_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_4/bd_c7bd_input_size_set_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_input_size_set_0 || ORIG_REF_NAME==bd_c7bd_input_size_set_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_5/bd_c7bd_rst_axis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_rst_axis_0 || ORIG_REF_NAME==bd_c7bd_rst_axis_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_6/bd_c7bd_reset_sel_axis_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_reset_sel_axis_0 || ORIG_REF_NAME==bd_c7bd_reset_sel_axis_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_7/bd_c7bd_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_axis_register_slice_0_0 || ORIG_REF_NAME==bd_c7bd_axis_register_slice_0_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_8/bd_c7bd_axis_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_axis_fifo_0 || ORIG_REF_NAME==bd_c7bd_axis_fifo_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_9/bd_c7bd_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_xlslice_0_0 || ORIG_REF_NAME==bd_c7bd_xlslice_0_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_10/bd_c7bd_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_xlslice_1_0 || ORIG_REF_NAME==bd_c7bd_xlslice_1_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_1/bd_c7bd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_xbar_0 || ORIG_REF_NAME==bd_c7bd_xbar_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_13/bd_c7bd_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_auto_cc_2 || ORIG_REF_NAME==bd_c7bd_auto_cc_2} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_12/bd_c7bd_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_auto_cc_1 || ORIG_REF_NAME==bd_c7bd_auto_cc_1} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_11/bd_c7bd_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_auto_cc_0 || ORIG_REF_NAME==bd_c7bd_auto_cc_0} -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/bd_c7bd_ooc.xdc

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/design_1_v_proc_ss_scaler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_proc_ss_scaler_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/design_1_v_proc_ss_scaler_0.xci
# IP: The module: 'design_1_v_proc_ss_scaler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/bd_c7bd.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd || ORIG_REF_NAME==bd_c7bd} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_0/bd_c7bd_axi_interconnect_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_axi_interconnect_0_0 || ORIG_REF_NAME==bd_c7bd_axi_interconnect_0_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_2/bd_c7bd_vsc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_vsc_0 || ORIG_REF_NAME==bd_c7bd_vsc_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_3/bd_c7bd_hsc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_hsc_0 || ORIG_REF_NAME==bd_c7bd_hsc_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_4/bd_c7bd_input_size_set_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_input_size_set_0 || ORIG_REF_NAME==bd_c7bd_input_size_set_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_5/bd_c7bd_rst_axis_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_rst_axis_0 || ORIG_REF_NAME==bd_c7bd_rst_axis_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_6/bd_c7bd_reset_sel_axis_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_reset_sel_axis_0 || ORIG_REF_NAME==bd_c7bd_reset_sel_axis_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_7/bd_c7bd_axis_register_slice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_axis_register_slice_0_0 || ORIG_REF_NAME==bd_c7bd_axis_register_slice_0_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_8/bd_c7bd_axis_fifo_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_axis_fifo_0 || ORIG_REF_NAME==bd_c7bd_axis_fifo_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_9/bd_c7bd_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_xlslice_0_0 || ORIG_REF_NAME==bd_c7bd_xlslice_0_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_10/bd_c7bd_xlslice_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_xlslice_1_0 || ORIG_REF_NAME==bd_c7bd_xlslice_1_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_1/bd_c7bd_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_xbar_0 || ORIG_REF_NAME==bd_c7bd_xbar_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_13/bd_c7bd_auto_cc_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_auto_cc_2 || ORIG_REF_NAME==bd_c7bd_auto_cc_2} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_12/bd_c7bd_auto_cc_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_auto_cc_1 || ORIG_REF_NAME==bd_c7bd_auto_cc_1} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/ip/ip_11/bd_c7bd_auto_cc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c7bd_auto_cc_0 || ORIG_REF_NAME==bd_c7bd_auto_cc_0} -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/bd_0/bd_c7bd_ooc.xdc

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_scaler_0/design_1_v_proc_ss_scaler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_proc_ss_scaler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
