# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_0/mipi_csi2_rx_ctrl_v1_0_6_fifo1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_1/mipi_csi2_rx_ctrl_v1_0_6_fc_644096.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fc_644096 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fc_644096} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_2/mipi_csi2_rx_ctrl_v1_0_6_fifo0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo0 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_3/mipi_csi2_rx_ctrl_v1_0_6_fifo2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2} -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_0/mipi_csi2_rx_ctrl_v1_0_6_fifo1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_0/mipi_csi2_rx_ctrl_v1_0_6_fifo1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_1/mipi_csi2_rx_ctrl_v1_0_6_fc_644096.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fc_644096 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fc_644096} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_2/mipi_csi2_rx_ctrl_v1_0_6_fifo0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo0 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_3/mipi_csi2_rx_ctrl_v1_0_6_fifo2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_3/mipi_csi2_rx_ctrl_v1_0_6_fifo2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/bd_7fd4_rx_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7fd4_rx_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/bd_7fd4_rx_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7fd4_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/bd_7fd4_rx_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7fd4_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_0/mipi_csi2_rx_ctrl_v1_0_6_fifo1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_1/mipi_csi2_rx_ctrl_v1_0_6_fc_644096.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fc_644096 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fc_644096} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_2/mipi_csi2_rx_ctrl_v1_0_6_fifo0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo0 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_3/mipi_csi2_rx_ctrl_v1_0_6_fifo2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2} -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_0/mipi_csi2_rx_ctrl_v1_0_6_fifo1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_0/mipi_csi2_rx_ctrl_v1_0_6_fifo1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_1/mipi_csi2_rx_ctrl_v1_0_6_fc_644096.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fc_644096 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fc_644096} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_2/mipi_csi2_rx_ctrl_v1_0_6_fifo0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo0 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_3/mipi_csi2_rx_ctrl_v1_0_6_fifo2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/ip_3/mipi_csi2_rx_ctrl_v1_0_6_fifo2_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2 || ORIG_REF_NAME==mipi_csi2_rx_ctrl_v1_0_6_fifo2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/bd_7fd4_rx_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7fd4_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/bd_7fd4_rx_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7fd4_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_1/bd_7fd4_rx_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7fd4_rx_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
