# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_3/ip_0/bd_7fd4_vfb_0_0_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7fd4_vfb_0_0_fifo || ORIG_REF_NAME==bd_7fd4_vfb_0_0_fifo} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_3/ip_1/bd_7fd4_vfb_0_0_axis_converter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7fd4_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_7fd4_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_3/ip_0/bd_7fd4_vfb_0_0_fifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7fd4_vfb_0_0_fifo || ORIG_REF_NAME==bd_7fd4_vfb_0_0_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_3/ip_0/bd_7fd4_vfb_0_0_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7fd4_vfb_0_0_fifo || ORIG_REF_NAME==bd_7fd4_vfb_0_0_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_3/bd_7fd4_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7fd4_vfb_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_3/ip_0/bd_7fd4_vfb_0_0_fifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7fd4_vfb_0_0_fifo || ORIG_REF_NAME==bd_7fd4_vfb_0_0_fifo} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_3/ip_1/bd_7fd4_vfb_0_0_axis_converter.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_7fd4_vfb_0_0_axis_converter || ORIG_REF_NAME==bd_7fd4_vfb_0_0_axis_converter} -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_3/ip_0/bd_7fd4_vfb_0_0_fifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7fd4_vfb_0_0_fifo || ORIG_REF_NAME==bd_7fd4_vfb_0_0_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_3/ip_0/bd_7fd4_vfb_0_0_fifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_7fd4_vfb_0_0_fifo || ORIG_REF_NAME==bd_7fd4_vfb_0_0_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_1/bd_0/ip/ip_3/bd_7fd4_vfb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_7fd4_vfb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
