-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.3
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_c7bd_hsc_0_v_hscaler_entry334 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    HwReg_Height : IN STD_LOGIC_VECTOR (15 downto 0);
    HwReg_WidthIn : IN STD_LOGIC_VECTOR (15 downto 0);
    HwReg_WidthOut : IN STD_LOGIC_VECTOR (15 downto 0);
    HwReg_ColorMode : IN STD_LOGIC_VECTOR (7 downto 0);
    HwReg_ColorModeOut : IN STD_LOGIC_VECTOR (7 downto 0);
    HwReg_Height_c_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    HwReg_Height_c_full_n : IN STD_LOGIC;
    HwReg_Height_c_write : OUT STD_LOGIC;
    HwReg_WidthIn_c_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    HwReg_WidthIn_c_full_n : IN STD_LOGIC;
    HwReg_WidthIn_c_write : OUT STD_LOGIC;
    HwReg_WidthOut_c_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    HwReg_WidthOut_c_full_n : IN STD_LOGIC;
    HwReg_WidthOut_c_write : OUT STD_LOGIC;
    HwReg_ColorMode_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    HwReg_ColorMode_c_full_n : IN STD_LOGIC;
    HwReg_ColorMode_c_write : OUT STD_LOGIC;
    HwReg_ColorMode_c32_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    HwReg_ColorMode_c32_full_n : IN STD_LOGIC;
    HwReg_ColorMode_c32_write : OUT STD_LOGIC;
    HwReg_ColorMode_c33_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    HwReg_ColorMode_c33_full_n : IN STD_LOGIC;
    HwReg_ColorMode_c33_write : OUT STD_LOGIC;
    HwReg_ColorModeOut_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    HwReg_ColorModeOut_c_full_n : IN STD_LOGIC;
    HwReg_ColorModeOut_c_write : OUT STD_LOGIC;
    HwReg_ColorModeOut_c_2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    HwReg_ColorModeOut_c_2_full_n : IN STD_LOGIC;
    HwReg_ColorModeOut_c_2_write : OUT STD_LOGIC;
    HwReg_ColorModeOut_c_1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    HwReg_ColorModeOut_c_1_full_n : IN STD_LOGIC;
    HwReg_ColorModeOut_c_1_write : OUT STD_LOGIC );
end;


architecture behav of bd_c7bd_hsc_0_v_hscaler_entry334 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal HwReg_Height_c_blk_n : STD_LOGIC;
    signal HwReg_WidthIn_c_blk_n : STD_LOGIC;
    signal HwReg_WidthOut_c_blk_n : STD_LOGIC;
    signal HwReg_ColorMode_c_blk_n : STD_LOGIC;
    signal HwReg_ColorMode_c32_blk_n : STD_LOGIC;
    signal HwReg_ColorMode_c33_blk_n : STD_LOGIC;
    signal HwReg_ColorModeOut_c_blk_n : STD_LOGIC;
    signal HwReg_ColorModeOut_c_2_blk_n : STD_LOGIC;
    signal HwReg_ColorModeOut_c_1_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = real_start)) then 
                    start_once_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    HwReg_ColorModeOut_c_1_blk_n_assign_proc : process(ap_CS_fsm_state1, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            HwReg_ColorModeOut_c_1_blk_n <= HwReg_ColorModeOut_c_1_full_n;
        else 
            HwReg_ColorModeOut_c_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_ColorModeOut_c_1_din <= HwReg_ColorModeOut;

    HwReg_ColorModeOut_c_1_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_ColorModeOut_c_1_write <= ap_const_logic_1;
        else 
            HwReg_ColorModeOut_c_1_write <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_ColorModeOut_c_2_blk_n_assign_proc : process(ap_CS_fsm_state1, HwReg_ColorModeOut_c_2_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            HwReg_ColorModeOut_c_2_blk_n <= HwReg_ColorModeOut_c_2_full_n;
        else 
            HwReg_ColorModeOut_c_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_ColorModeOut_c_2_din <= HwReg_ColorModeOut;

    HwReg_ColorModeOut_c_2_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_ColorModeOut_c_2_write <= ap_const_logic_1;
        else 
            HwReg_ColorModeOut_c_2_write <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_ColorModeOut_c_blk_n_assign_proc : process(ap_CS_fsm_state1, HwReg_ColorModeOut_c_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            HwReg_ColorModeOut_c_blk_n <= HwReg_ColorModeOut_c_full_n;
        else 
            HwReg_ColorModeOut_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_ColorModeOut_c_din <= HwReg_ColorModeOut;

    HwReg_ColorModeOut_c_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_ColorModeOut_c_write <= ap_const_logic_1;
        else 
            HwReg_ColorModeOut_c_write <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_ColorMode_c32_blk_n_assign_proc : process(ap_CS_fsm_state1, HwReg_ColorMode_c32_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            HwReg_ColorMode_c32_blk_n <= HwReg_ColorMode_c32_full_n;
        else 
            HwReg_ColorMode_c32_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_ColorMode_c32_din <= HwReg_ColorMode;

    HwReg_ColorMode_c32_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_ColorMode_c32_write <= ap_const_logic_1;
        else 
            HwReg_ColorMode_c32_write <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_ColorMode_c33_blk_n_assign_proc : process(ap_CS_fsm_state1, HwReg_ColorMode_c33_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            HwReg_ColorMode_c33_blk_n <= HwReg_ColorMode_c33_full_n;
        else 
            HwReg_ColorMode_c33_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_ColorMode_c33_din <= HwReg_ColorMode;

    HwReg_ColorMode_c33_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_ColorMode_c33_write <= ap_const_logic_1;
        else 
            HwReg_ColorMode_c33_write <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_ColorMode_c_blk_n_assign_proc : process(ap_CS_fsm_state1, HwReg_ColorMode_c_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            HwReg_ColorMode_c_blk_n <= HwReg_ColorMode_c_full_n;
        else 
            HwReg_ColorMode_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_ColorMode_c_din <= HwReg_ColorMode;

    HwReg_ColorMode_c_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_ColorMode_c_write <= ap_const_logic_1;
        else 
            HwReg_ColorMode_c_write <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_Height_c_blk_n_assign_proc : process(ap_CS_fsm_state1, HwReg_Height_c_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            HwReg_Height_c_blk_n <= HwReg_Height_c_full_n;
        else 
            HwReg_Height_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_Height_c_din <= HwReg_Height(12 - 1 downto 0);

    HwReg_Height_c_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_Height_c_write <= ap_const_logic_1;
        else 
            HwReg_Height_c_write <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_WidthIn_c_blk_n_assign_proc : process(ap_CS_fsm_state1, HwReg_WidthIn_c_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            HwReg_WidthIn_c_blk_n <= HwReg_WidthIn_c_full_n;
        else 
            HwReg_WidthIn_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_WidthIn_c_din <= HwReg_WidthIn(12 - 1 downto 0);

    HwReg_WidthIn_c_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_WidthIn_c_write <= ap_const_logic_1;
        else 
            HwReg_WidthIn_c_write <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_WidthOut_c_blk_n_assign_proc : process(ap_CS_fsm_state1, HwReg_WidthOut_c_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            HwReg_WidthOut_c_blk_n <= HwReg_WidthOut_c_full_n;
        else 
            HwReg_WidthOut_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_WidthOut_c_din <= HwReg_WidthOut(12 - 1 downto 0);

    HwReg_WidthOut_c_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_WidthOut_c_write <= ap_const_logic_1;
        else 
            HwReg_WidthOut_c_write <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = real_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    internal_ap_ready_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, HwReg_Height_c_full_n, HwReg_WidthIn_c_full_n, HwReg_WidthOut_c_full_n, HwReg_ColorMode_c_full_n, HwReg_ColorMode_c32_full_n, HwReg_ColorMode_c33_full_n, HwReg_ColorModeOut_c_full_n, HwReg_ColorModeOut_c_2_full_n, HwReg_ColorModeOut_c_1_full_n)
    begin
        if ((not(((ap_const_logic_0 = HwReg_ColorModeOut_c_1_full_n) or (ap_const_logic_0 = HwReg_ColorModeOut_c_2_full_n) or (ap_const_logic_0 = real_start) or (ap_const_logic_0 = HwReg_ColorModeOut_c_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c33_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c32_full_n) or (ap_const_logic_0 = HwReg_ColorMode_c_full_n) or (ap_const_logic_0 = HwReg_WidthOut_c_full_n) or (ap_const_logic_0 = HwReg_WidthIn_c_full_n) or (ap_const_logic_0 = HwReg_Height_c_full_n) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n)
    begin
        if ((ap_const_logic_0 = start_full_n)) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, internal_ap_ready, start_once_reg)
    begin
        if (((ap_const_logic_1 = real_start) and ((ap_const_logic_0 = start_once_reg) or (ap_const_logic_1 = internal_ap_ready)))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
