# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0.xci
# IP: The module: 'design_1_mipi_csi2_rx_subsystem_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/bd_bf15.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bf15 || ORIG_REF_NAME==bd_bf15} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_0/bd_bf15_r_sync_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bf15_r_sync_0 || ORIG_REF_NAME==bd_bf15_r_sync_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_1/bd_bf15_rx_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bf15_rx_0 || ORIG_REF_NAME==bd_bf15_rx_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_2/bd_bf15_phy_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bf15_phy_0 || ORIG_REF_NAME==bd_bf15_phy_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf15_vfb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bf15_vfb_0_0 || ORIG_REF_NAME==bd_bf15_vfb_0_0} -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/bd_bf15_ooc.xdc

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsystem_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsystem_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0.xci
# IP: The module: 'design_1_mipi_csi2_rx_subsystem_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/bd_bf15.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bf15 || ORIG_REF_NAME==bd_bf15} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_0/bd_bf15_r_sync_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bf15_r_sync_0 || ORIG_REF_NAME==bd_bf15_r_sync_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_1/bd_bf15_rx_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bf15_rx_0 || ORIG_REF_NAME==bd_bf15_rx_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_2/bd_bf15_phy_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bf15_phy_0 || ORIG_REF_NAME==bd_bf15_phy_0} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/ip/ip_3/bd_bf15_vfb_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_bf15_vfb_0_0 || ORIG_REF_NAME==bd_bf15_vfb_0_0} -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/bd_0/bd_bf15_ooc.xdc

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsystem_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_mipi_csi2_rx_subsystem_0_0/design_1_mipi_csi2_rx_subsystem_0_0_fixed_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mipi_csi2_rx_subsystem_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
