# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_csc_0/design_1_v_proc_ss_csc_0.xci
# IP: The module: 'design_1_v_proc_ss_csc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_csc_0/bd_0/bd_039a.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_039a || ORIG_REF_NAME==bd_039a} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_csc_0/bd_0/ip/ip_0/bd_039a_csc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_039a_csc_0 || ORIG_REF_NAME==bd_039a_csc_0} -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_csc_0/bd_0/bd_039a_ooc.xdc

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_csc_0/design_1_v_proc_ss_csc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_proc_ss_csc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_csc_0/design_1_v_proc_ss_csc_0.xci
# IP: The module: 'design_1_v_proc_ss_csc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_csc_0/bd_0/bd_039a.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_039a || ORIG_REF_NAME==bd_039a} -quiet] -quiet

# IP: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_csc_0/bd_0/ip/ip_0/bd_039a_csc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_039a_csc_0 || ORIG_REF_NAME==bd_039a_csc_0} -quiet] -quiet

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_csc_0/bd_0/bd_039a_ooc.xdc

# XDC: /home/ad2039/G00StereoCamera/SCAM/SCAM.srcs/sources_1/bd/design_1/ip/design_1_v_proc_ss_csc_0/design_1_v_proc_ss_csc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_proc_ss_csc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
