-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.3
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_039a_csc_0_MultiPixStream2AXIvi is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_csc_V_val_0_s_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_csc_V_val_0_s_empty_n : IN STD_LOGIC;
    stream_csc_V_val_0_s_read : OUT STD_LOGIC;
    stream_csc_V_val_1_s_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_csc_V_val_1_s_empty_n : IN STD_LOGIC;
    stream_csc_V_val_1_s_read : OUT STD_LOGIC;
    stream_csc_V_val_2_s_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_csc_V_val_2_s_empty_n : IN STD_LOGIC;
    stream_csc_V_val_2_s_read : OUT STD_LOGIC;
    stream_csc_V_val_3_s_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_csc_V_val_3_s_empty_n : IN STD_LOGIC;
    stream_csc_V_val_3_s_read : OUT STD_LOGIC;
    stream_csc_V_val_4_s_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_csc_V_val_4_s_empty_n : IN STD_LOGIC;
    stream_csc_V_val_4_s_read : OUT STD_LOGIC;
    stream_csc_V_val_5_s_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    stream_csc_V_val_5_s_empty_n : IN STD_LOGIC;
    stream_csc_V_val_5_s_read : OUT STD_LOGIC;
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (5 downto 0);
    m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (5 downto 0);
    m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    HwReg_height : IN STD_LOGIC_VECTOR (15 downto 0);
    HwReg_width : IN STD_LOGIC_VECTOR (15 downto 0);
    HwReg_OutVideoFormat : IN STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of bd_039a_csc_0_MultiPixStream2AXIvi is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv40_FFFFFFFFFF : STD_LOGIC_VECTOR (39 downto 0) := "1111111111111111111111111111111111111111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal m_axis_video_V_data_V_1_data_out : STD_LOGIC_VECTOR (47 downto 0);
    signal m_axis_video_V_data_V_1_vld_in : STD_LOGIC;
    signal m_axis_video_V_data_V_1_vld_out : STD_LOGIC;
    signal m_axis_video_V_data_V_1_ack_in : STD_LOGIC;
    signal m_axis_video_V_data_V_1_ack_out : STD_LOGIC;
    signal m_axis_video_V_data_V_1_payload_A : STD_LOGIC_VECTOR (47 downto 0);
    signal m_axis_video_V_data_V_1_payload_B : STD_LOGIC_VECTOR (47 downto 0);
    signal m_axis_video_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_video_V_data_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_video_V_data_V_1_sel : STD_LOGIC;
    signal m_axis_video_V_data_V_1_load_A : STD_LOGIC;
    signal m_axis_video_V_data_V_1_load_B : STD_LOGIC;
    signal m_axis_video_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_video_V_data_V_1_state_cmp_full : STD_LOGIC;
    signal m_axis_video_V_keep_V_1_data_out : STD_LOGIC_VECTOR (5 downto 0);
    signal m_axis_video_V_keep_V_1_vld_in : STD_LOGIC;
    signal m_axis_video_V_keep_V_1_vld_out : STD_LOGIC;
    signal m_axis_video_V_keep_V_1_ack_in : STD_LOGIC;
    signal m_axis_video_V_keep_V_1_ack_out : STD_LOGIC;
    signal m_axis_video_V_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_video_V_keep_V_1_sel : STD_LOGIC;
    signal m_axis_video_V_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_video_V_strb_V_1_data_out : STD_LOGIC_VECTOR (5 downto 0);
    signal m_axis_video_V_strb_V_1_vld_in : STD_LOGIC;
    signal m_axis_video_V_strb_V_1_vld_out : STD_LOGIC;
    signal m_axis_video_V_strb_V_1_ack_in : STD_LOGIC;
    signal m_axis_video_V_strb_V_1_ack_out : STD_LOGIC;
    signal m_axis_video_V_strb_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_video_V_strb_V_1_sel : STD_LOGIC;
    signal m_axis_video_V_strb_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_video_V_user_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_V_user_V_1_vld_in : STD_LOGIC;
    signal m_axis_video_V_user_V_1_vld_out : STD_LOGIC;
    signal m_axis_video_V_user_V_1_ack_in : STD_LOGIC;
    signal m_axis_video_V_user_V_1_ack_out : STD_LOGIC;
    signal m_axis_video_V_user_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_V_user_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_V_user_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_video_V_user_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_video_V_user_V_1_sel : STD_LOGIC;
    signal m_axis_video_V_user_V_1_load_A : STD_LOGIC;
    signal m_axis_video_V_user_V_1_load_B : STD_LOGIC;
    signal m_axis_video_V_user_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_video_V_user_V_1_state_cmp_full : STD_LOGIC;
    signal m_axis_video_V_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_V_last_V_1_vld_in : STD_LOGIC;
    signal m_axis_video_V_last_V_1_vld_out : STD_LOGIC;
    signal m_axis_video_V_last_V_1_ack_in : STD_LOGIC;
    signal m_axis_video_V_last_V_1_ack_out : STD_LOGIC;
    signal m_axis_video_V_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_V_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_V_last_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_video_V_last_V_1_sel_wr : STD_LOGIC := '0';
    signal m_axis_video_V_last_V_1_sel : STD_LOGIC;
    signal m_axis_video_V_last_V_1_load_A : STD_LOGIC;
    signal m_axis_video_V_last_V_1_load_B : STD_LOGIC;
    signal m_axis_video_V_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_video_V_last_V_1_state_cmp_full : STD_LOGIC;
    signal m_axis_video_V_id_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_V_id_V_1_vld_in : STD_LOGIC;
    signal m_axis_video_V_id_V_1_vld_out : STD_LOGIC;
    signal m_axis_video_V_id_V_1_ack_in : STD_LOGIC;
    signal m_axis_video_V_id_V_1_ack_out : STD_LOGIC;
    signal m_axis_video_V_id_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_video_V_id_V_1_sel : STD_LOGIC;
    signal m_axis_video_V_id_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal m_axis_video_V_dest_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_V_dest_V_1_vld_in : STD_LOGIC;
    signal m_axis_video_V_dest_V_1_vld_out : STD_LOGIC;
    signal m_axis_video_V_dest_V_1_ack_in : STD_LOGIC;
    signal m_axis_video_V_dest_V_1_ack_out : STD_LOGIC;
    signal m_axis_video_V_dest_V_1_sel_rd : STD_LOGIC := '0';
    signal m_axis_video_V_dest_V_1_sel : STD_LOGIC;
    signal m_axis_video_V_dest_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal stream_csc_V_val_0_s_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal exitcond_i_reg_566 : STD_LOGIC_VECTOR (0 downto 0);
    signal stream_csc_V_val_1_s_blk_n : STD_LOGIC;
    signal stream_csc_V_val_2_s_blk_n : STD_LOGIC;
    signal stream_csc_V_val_3_s_blk_n : STD_LOGIC;
    signal stream_csc_V_val_4_s_blk_n : STD_LOGIC;
    signal stream_csc_V_val_5_s_blk_n : STD_LOGIC;
    signal m_axis_video_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_reg_pp0_iter1_exitcond_i_reg_566 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_i_i_reg_270 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal grp_reg_unsigned_short_s_fu_289_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_i_i_reg_524 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_reg_unsigned_short_s_fu_289_ap_done : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_295_ap_done : STD_LOGIC;
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal tmp_12_cast_i_i_fu_306_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_12_cast_i_i_reg_529 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_13_i_i_fu_316_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_13_i_i_reg_534 : STD_LOGIC_VECTOR (10 downto 0);
    signal sel_tmp_i_fu_322_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_i_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond1_i_i_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_block_state3 : BOOLEAN;
    signal i_fu_339_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal i_reg_561 : STD_LOGIC_VECTOR (11 downto 0);
    signal exitcond_i_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_pp0_stage0_iter0 : BOOLEAN;
    signal stream_csc_V_val_0_s0_status : STD_LOGIC;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal j_fu_350_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal axi_last_V_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V_reg_575 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_data_V_fu_489_p5 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state4 : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_289_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_289_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_289_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_289_in_r : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_reg_unsigned_short_s_fu_295_ap_start : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_295_ap_idle : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_295_ap_ready : STD_LOGIC;
    signal grp_reg_unsigned_short_s_fu_295_in_r : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_reg_unsigned_short_s_fu_295_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal i_i_i_reg_259 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_reg_grp_reg_unsigned_short_s_fu_289_ap_start : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call13 : BOOLEAN;
    signal ap_reg_grp_reg_unsigned_short_s_fu_295_ap_start : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call14 : BOOLEAN;
    signal stream_csc_V_val_0_s0_update : STD_LOGIC;
    signal tmp_user_V_fu_192 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_Result_0_i_i_fu_397_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal p_Result_2_0_i_i_fu_389_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_i_73_fu_419_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_i_fu_433_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_i_fu_447_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_i_fu_461_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_i_fu_468_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_i_fu_454_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_i_fu_440_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_i_fu_426_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_i_fu_412_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal axi_0_2_0_i_i_fu_405_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_9_i_fu_475_p6 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component bd_039a_csc_0_reg_unsigned_short_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_r : IN STD_LOGIC_VECTOR (11 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;



begin
    grp_reg_unsigned_short_s_fu_289 : component bd_039a_csc_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_289_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_289_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_289_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_289_ap_ready,
        in_r => grp_reg_unsigned_short_s_fu_289_in_r,
        ap_return => grp_reg_unsigned_short_s_fu_289_ap_return);

    grp_reg_unsigned_short_s_fu_295 : component bd_039a_csc_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_reg_unsigned_short_s_fu_295_ap_start,
        ap_done => grp_reg_unsigned_short_s_fu_295_ap_done,
        ap_idle => grp_reg_unsigned_short_s_fu_295_ap_idle,
        ap_ready => grp_reg_unsigned_short_s_fu_295_ap_ready,
        in_r => grp_reg_unsigned_short_s_fu_295_in_r,
        ap_return => grp_reg_unsigned_short_s_fu_295_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_in))) and (ap_const_lv1_1 = exitcond1_i_i_fu_334_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_block_pp0_stage0_subdone = ap_const_boolean_0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_in))) and (ap_const_lv1_0 = exitcond1_i_i_fu_334_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state4 xor ap_const_logic_1);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_subdone = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((not(((ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_in))) and (ap_const_lv1_0 = exitcond1_i_i_fu_334_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_reg_unsigned_short_s_fu_289_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_reg_unsigned_short_s_fu_289_ap_start <= ap_const_logic_0;
            else
                if ((not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_reg_grp_reg_unsigned_short_s_fu_289_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_reg_unsigned_short_s_fu_289_ap_ready)) then 
                    ap_reg_grp_reg_unsigned_short_s_fu_289_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_reg_unsigned_short_s_fu_295_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_reg_unsigned_short_s_fu_295_ap_start <= ap_const_logic_0;
            else
                if ((not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_reg_grp_reg_unsigned_short_s_fu_295_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_reg_unsigned_short_s_fu_295_ap_ready)) then 
                    ap_reg_grp_reg_unsigned_short_s_fu_295_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = m_axis_video_V_data_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_data_V_1_vld_out))) then 
                                        m_axis_video_V_data_V_1_sel_rd <= not(m_axis_video_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = m_axis_video_V_data_V_1_ack_in) and (ap_const_logic_1 = m_axis_video_V_data_V_1_vld_in))) then 
                                        m_axis_video_V_data_V_1_sel_wr <= not(m_axis_video_V_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((m_axis_video_V_data_V_1_state = ap_const_lv2_2) and (ap_const_logic_0 = m_axis_video_V_data_V_1_vld_in)) or ((m_axis_video_V_data_V_1_state = ap_const_lv2_3) and (ap_const_logic_0 = m_axis_video_V_data_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_data_V_1_ack_out)))) then 
                    m_axis_video_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((m_axis_video_V_data_V_1_state = ap_const_lv2_1) and (ap_const_logic_0 = m_axis_video_V_data_V_1_ack_out)) or ((m_axis_video_V_data_V_1_state = ap_const_lv2_3) and (ap_const_logic_0 = m_axis_video_V_data_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_data_V_1_vld_in)))) then 
                    m_axis_video_V_data_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = m_axis_video_V_data_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_data_V_1_ack_out))) and not(((ap_const_logic_0 = m_axis_video_V_data_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_data_V_1_vld_in))) and (m_axis_video_V_data_V_1_state = ap_const_lv2_3)) or ((m_axis_video_V_data_V_1_state = ap_const_lv2_1) and (ap_const_logic_1 = m_axis_video_V_data_V_1_ack_out)) or ((m_axis_video_V_data_V_1_state = ap_const_lv2_2) and (ap_const_logic_1 = m_axis_video_V_data_V_1_vld_in)))) then 
                    m_axis_video_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_video_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_dest_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_dest_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = m_axis_video_V_dest_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_dest_V_1_vld_out))) then 
                                        m_axis_video_V_dest_V_1_sel_rd <= not(m_axis_video_V_dest_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_dest_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_dest_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = m_axis_video_V_dest_V_1_state) and (ap_const_logic_0 = m_axis_video_V_dest_V_1_vld_in)) or ((ap_const_lv2_3 = m_axis_video_V_dest_V_1_state) and (ap_const_logic_0 = m_axis_video_V_dest_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_dest_V_1_ack_out)))) then 
                    m_axis_video_V_dest_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = m_axis_video_V_dest_V_1_state) and (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_out)) or ((ap_const_lv2_3 = m_axis_video_V_dest_V_1_state) and (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_dest_V_1_vld_in)))) then 
                    m_axis_video_V_dest_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = m_axis_video_V_dest_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_dest_V_1_ack_out))) and not(((ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_dest_V_1_vld_in))) and (ap_const_lv2_3 = m_axis_video_V_dest_V_1_state)) or ((ap_const_lv2_1 = m_axis_video_V_dest_V_1_state) and (ap_const_logic_1 = m_axis_video_V_dest_V_1_ack_out)) or ((ap_const_lv2_2 = m_axis_video_V_dest_V_1_state) and (ap_const_logic_1 = m_axis_video_V_dest_V_1_vld_in)))) then 
                    m_axis_video_V_dest_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_video_V_dest_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_id_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_id_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = m_axis_video_V_id_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_id_V_1_vld_out))) then 
                                        m_axis_video_V_id_V_1_sel_rd <= not(m_axis_video_V_id_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_id_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_id_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = m_axis_video_V_id_V_1_state) and (ap_const_logic_0 = m_axis_video_V_id_V_1_vld_in)) or ((ap_const_lv2_3 = m_axis_video_V_id_V_1_state) and (ap_const_logic_0 = m_axis_video_V_id_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_id_V_1_ack_out)))) then 
                    m_axis_video_V_id_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = m_axis_video_V_id_V_1_state) and (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_out)) or ((ap_const_lv2_3 = m_axis_video_V_id_V_1_state) and (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_id_V_1_vld_in)))) then 
                    m_axis_video_V_id_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = m_axis_video_V_id_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_id_V_1_ack_out))) and not(((ap_const_logic_0 = m_axis_video_V_id_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_id_V_1_vld_in))) and (ap_const_lv2_3 = m_axis_video_V_id_V_1_state)) or ((ap_const_lv2_1 = m_axis_video_V_id_V_1_state) and (ap_const_logic_1 = m_axis_video_V_id_V_1_ack_out)) or ((ap_const_lv2_2 = m_axis_video_V_id_V_1_state) and (ap_const_logic_1 = m_axis_video_V_id_V_1_vld_in)))) then 
                    m_axis_video_V_id_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_video_V_id_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = m_axis_video_V_keep_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_keep_V_1_vld_out))) then 
                                        m_axis_video_V_keep_V_1_sel_rd <= not(m_axis_video_V_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = m_axis_video_V_keep_V_1_state) and (ap_const_logic_0 = m_axis_video_V_keep_V_1_vld_in)) or ((ap_const_lv2_3 = m_axis_video_V_keep_V_1_state) and (ap_const_logic_0 = m_axis_video_V_keep_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_keep_V_1_ack_out)))) then 
                    m_axis_video_V_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = m_axis_video_V_keep_V_1_state) and (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_out)) or ((ap_const_lv2_3 = m_axis_video_V_keep_V_1_state) and (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_keep_V_1_vld_in)))) then 
                    m_axis_video_V_keep_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = m_axis_video_V_keep_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_keep_V_1_ack_out))) and not(((ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_keep_V_1_vld_in))) and (ap_const_lv2_3 = m_axis_video_V_keep_V_1_state)) or ((ap_const_lv2_1 = m_axis_video_V_keep_V_1_state) and (ap_const_logic_1 = m_axis_video_V_keep_V_1_ack_out)) or ((ap_const_lv2_2 = m_axis_video_V_keep_V_1_state) and (ap_const_logic_1 = m_axis_video_V_keep_V_1_vld_in)))) then 
                    m_axis_video_V_keep_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_video_V_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = m_axis_video_V_last_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_last_V_1_vld_out))) then 
                                        m_axis_video_V_last_V_1_sel_rd <= not(m_axis_video_V_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = m_axis_video_V_last_V_1_ack_in) and (ap_const_logic_1 = m_axis_video_V_last_V_1_vld_in))) then 
                                        m_axis_video_V_last_V_1_sel_wr <= not(m_axis_video_V_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = m_axis_video_V_last_V_1_state) and (ap_const_logic_0 = m_axis_video_V_last_V_1_vld_in)) or ((ap_const_lv2_3 = m_axis_video_V_last_V_1_state) and (ap_const_logic_0 = m_axis_video_V_last_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_last_V_1_ack_out)))) then 
                    m_axis_video_V_last_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = m_axis_video_V_last_V_1_state) and (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_out)) or ((ap_const_lv2_3 = m_axis_video_V_last_V_1_state) and (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_last_V_1_vld_in)))) then 
                    m_axis_video_V_last_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = m_axis_video_V_last_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_last_V_1_ack_out))) and not(((ap_const_logic_0 = m_axis_video_V_last_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_last_V_1_vld_in))) and (ap_const_lv2_3 = m_axis_video_V_last_V_1_state)) or ((ap_const_lv2_1 = m_axis_video_V_last_V_1_state) and (ap_const_logic_1 = m_axis_video_V_last_V_1_ack_out)) or ((ap_const_lv2_2 = m_axis_video_V_last_V_1_state) and (ap_const_logic_1 = m_axis_video_V_last_V_1_vld_in)))) then 
                    m_axis_video_V_last_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_video_V_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_strb_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_strb_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = m_axis_video_V_strb_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_strb_V_1_vld_out))) then 
                                        m_axis_video_V_strb_V_1_sel_rd <= not(m_axis_video_V_strb_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_strb_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_strb_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = m_axis_video_V_strb_V_1_state) and (ap_const_logic_0 = m_axis_video_V_strb_V_1_vld_in)) or ((ap_const_lv2_3 = m_axis_video_V_strb_V_1_state) and (ap_const_logic_0 = m_axis_video_V_strb_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_strb_V_1_ack_out)))) then 
                    m_axis_video_V_strb_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = m_axis_video_V_strb_V_1_state) and (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_out)) or ((ap_const_lv2_3 = m_axis_video_V_strb_V_1_state) and (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_strb_V_1_vld_in)))) then 
                    m_axis_video_V_strb_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = m_axis_video_V_strb_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_strb_V_1_ack_out))) and not(((ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_strb_V_1_vld_in))) and (ap_const_lv2_3 = m_axis_video_V_strb_V_1_state)) or ((ap_const_lv2_1 = m_axis_video_V_strb_V_1_state) and (ap_const_logic_1 = m_axis_video_V_strb_V_1_ack_out)) or ((ap_const_lv2_2 = m_axis_video_V_strb_V_1_state) and (ap_const_logic_1 = m_axis_video_V_strb_V_1_vld_in)))) then 
                    m_axis_video_V_strb_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_video_V_strb_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_user_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_user_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = m_axis_video_V_user_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_user_V_1_vld_out))) then 
                                        m_axis_video_V_user_V_1_sel_rd <= not(m_axis_video_V_user_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_user_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_user_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = m_axis_video_V_user_V_1_ack_in) and (ap_const_logic_1 = m_axis_video_V_user_V_1_vld_in))) then 
                                        m_axis_video_V_user_V_1_sel_wr <= not(m_axis_video_V_user_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    m_axis_video_V_user_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                m_axis_video_V_user_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_lv2_2 = m_axis_video_V_user_V_1_state) and (ap_const_logic_0 = m_axis_video_V_user_V_1_vld_in)) or ((ap_const_lv2_3 = m_axis_video_V_user_V_1_state) and (ap_const_logic_0 = m_axis_video_V_user_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_user_V_1_ack_out)))) then 
                    m_axis_video_V_user_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_lv2_1 = m_axis_video_V_user_V_1_state) and (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_out)) or ((ap_const_lv2_3 = m_axis_video_V_user_V_1_state) and (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_user_V_1_vld_in)))) then 
                    m_axis_video_V_user_V_1_state <= ap_const_lv2_1;
                elsif (((not(((ap_const_logic_0 = m_axis_video_V_user_V_1_vld_in) and (ap_const_logic_1 = m_axis_video_V_user_V_1_ack_out))) and not(((ap_const_logic_0 = m_axis_video_V_user_V_1_ack_out) and (ap_const_logic_1 = m_axis_video_V_user_V_1_vld_in))) and (ap_const_lv2_3 = m_axis_video_V_user_V_1_state)) or ((ap_const_lv2_1 = m_axis_video_V_user_V_1_state) and (ap_const_logic_1 = m_axis_video_V_user_V_1_ack_out)) or ((ap_const_lv2_2 = m_axis_video_V_user_V_1_state) and (ap_const_logic_1 = m_axis_video_V_user_V_1_vld_in)))) then 
                    m_axis_video_V_user_V_1_state <= ap_const_lv2_3;
                else 
                    m_axis_video_V_user_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    i_i_i_reg_259_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                i_i_i_reg_259 <= i_reg_561;
            elsif (((ap_block_state2_on_subcall_done = ap_const_boolean_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_i_i_reg_259 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    j_i_i_reg_270_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_in))) and (ap_const_lv1_0 = exitcond1_i_i_fu_334_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                j_i_i_reg_270 <= ap_const_lv11_0;
            elsif (((ap_const_lv1_0 = exitcond_i_fu_345_p2) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_i_i_reg_270 <= j_fu_350_p2;
            end if; 
        end if;
    end process;

    tmp_user_V_fu_192_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                tmp_user_V_fu_192 <= ap_const_lv1_0;
            elsif ((not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                tmp_user_V_fu_192 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_reg_pp0_iter1_exitcond_i_reg_566 <= exitcond_i_reg_566;
                exitcond_i_reg_566 <= exitcond_i_fu_345_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_0 = exitcond_i_fu_345_p2) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                axi_last_V_reg_575 <= axi_last_V_fu_356_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_in))) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                i_reg_561 <= i_fu_339_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = m_axis_video_V_data_V_1_load_A)) then
                m_axis_video_V_data_V_1_payload_A <= tmp_data_V_fu_489_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = m_axis_video_V_data_V_1_load_B)) then
                m_axis_video_V_data_V_1_payload_B <= tmp_data_V_fu_489_p5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = m_axis_video_V_last_V_1_load_A)) then
                m_axis_video_V_last_V_1_payload_A <= axi_last_V_reg_575;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = m_axis_video_V_last_V_1_load_B)) then
                m_axis_video_V_last_V_1_payload_B <= axi_last_V_reg_575;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = m_axis_video_V_user_V_1_load_A)) then
                m_axis_video_V_user_V_1_payload_A <= tmp_user_V_fu_192;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = m_axis_video_V_user_V_1_load_B)) then
                m_axis_video_V_user_V_1_payload_B <= tmp_user_V_fu_192;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_state2_on_subcall_done = ap_const_boolean_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tmp_12_cast_i_i_reg_529 <= grp_reg_unsigned_short_s_fu_295_ap_return(11 downto 1);
                tmp_13_i_i_reg_534 <= tmp_13_i_i_fu_316_p2;
                tmp_i_i_reg_524 <= grp_reg_unsigned_short_s_fu_289_ap_return;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, m_axis_video_V_data_V_1_ack_in, m_axis_video_V_keep_V_1_ack_in, m_axis_video_V_strb_V_1_ack_in, m_axis_video_V_user_V_1_ack_in, m_axis_video_V_last_V_1_ack_in, m_axis_video_V_id_V_1_ack_in, m_axis_video_V_dest_V_1_ack_in, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_CS_fsm_state2, ap_block_state2_on_subcall_done, exitcond1_i_i_fu_334_p2, ap_CS_fsm_state3, exitcond_i_fu_345_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_block_state2_on_subcall_done = ap_const_boolean_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not(((ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_in))) and (ap_const_lv1_1 = exitcond1_i_i_fu_334_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_in))) and (ap_const_lv1_0 = exitcond1_i_i_fu_334_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_lv1_1 = exitcond_i_fu_345_p2) and (ap_block_pp0_stage0_subdone = ap_const_boolean_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0))) and not(((ap_block_pp0_stage0_subdone = ap_const_boolean_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_const_lv1_1 = exitcond_i_fu_345_p2) and (ap_block_pp0_stage0_subdone = ap_const_boolean_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0)) or ((ap_block_pp0_stage0_subdone = ap_const_boolean_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2)))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state7 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, exitcond_i_reg_566, stream_csc_V_val_0_s0_status)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_const_logic_0 = stream_csc_V_val_0_s0_status) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, exitcond_i_reg_566, ap_enable_reg_pp0_iter2, stream_csc_V_val_0_s0_status, ap_block_state5_io, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_const_boolean_1 = ap_block_state6_io) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and ((ap_const_boolean_1 = ap_block_state5_io) or ((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_const_logic_0 = stream_csc_V_val_0_s0_status)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, exitcond_i_reg_566, ap_enable_reg_pp0_iter2, stream_csc_V_val_0_s0_status, ap_block_state5_io, ap_block_state6_io)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_const_boolean_1 = ap_block_state6_io) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and ((ap_const_boolean_1 = ap_block_state5_io) or ((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_const_logic_0 = stream_csc_V_val_0_s0_status)))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call13_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call13 <= ((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call14_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call14 <= ((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_on_subcall_done_assign_proc : process(grp_reg_unsigned_short_s_fu_289_ap_done, grp_reg_unsigned_short_s_fu_295_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((ap_const_logic_0 = grp_reg_unsigned_short_s_fu_295_ap_done) or (ap_const_logic_0 = grp_reg_unsigned_short_s_fu_289_ap_done));
    end process;


    ap_block_state3_assign_proc : process(m_axis_video_V_data_V_1_ack_in, m_axis_video_V_keep_V_1_ack_in, m_axis_video_V_strb_V_1_ack_in, m_axis_video_V_user_V_1_ack_in, m_axis_video_V_last_V_1_ack_in, m_axis_video_V_id_V_1_ack_in, m_axis_video_V_dest_V_1_ack_in)
    begin
                ap_block_state3 <= ((ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_in));
    end process;

        ap_block_state4_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_io_assign_proc : process(m_axis_video_V_data_V_1_ack_in, exitcond_i_reg_566)
    begin
                ap_block_state5_io <= ((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in));
    end process;


    ap_block_state5_pp0_stage0_iter1_assign_proc : process(exitcond_i_reg_566, stream_csc_V_val_0_s0_status)
    begin
                ap_block_state5_pp0_stage0_iter1 <= ((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_const_logic_0 = stream_csc_V_val_0_s0_status));
    end process;


    ap_block_state6_io_assign_proc : process(m_axis_video_V_data_V_1_ack_in, ap_reg_pp0_iter1_exitcond_i_reg_566)
    begin
                ap_block_state6_io <= ((ap_const_lv1_0 = ap_reg_pp0_iter1_exitcond_i_reg_566) and (ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in));
    end process;

        ap_block_state6_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state4_assign_proc : process(exitcond_i_fu_345_p2)
    begin
        if ((ap_const_lv1_1 = exitcond_i_fu_345_p2)) then 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, m_axis_video_V_data_V_1_ack_in, m_axis_video_V_keep_V_1_ack_in, m_axis_video_V_strb_V_1_ack_in, m_axis_video_V_user_V_1_ack_in, m_axis_video_V_last_V_1_ack_in, m_axis_video_V_id_V_1_ack_in, m_axis_video_V_dest_V_1_ack_in, exitcond1_i_i_fu_334_p2, ap_CS_fsm_state3)
    begin
        if ((not(((ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_in))) and (ap_const_lv1_1 = exitcond1_i_i_fu_334_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(m_axis_video_V_data_V_1_ack_in, m_axis_video_V_keep_V_1_ack_in, m_axis_video_V_strb_V_1_ack_in, m_axis_video_V_user_V_1_ack_in, m_axis_video_V_last_V_1_ack_in, m_axis_video_V_id_V_1_ack_in, m_axis_video_V_dest_V_1_ack_in, exitcond1_i_i_fu_334_p2, ap_CS_fsm_state3)
    begin
        if ((not(((ap_const_logic_0 = m_axis_video_V_data_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_dest_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_id_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_last_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_user_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_strb_V_1_ack_in) or (ap_const_logic_0 = m_axis_video_V_keep_V_1_ack_in))) and (ap_const_lv1_1 = exitcond1_i_i_fu_334_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    axi_0_2_0_i_i_fu_405_p3 <= 
        p_Result_0_i_i_fu_397_p3 when (sel_tmp2_i_fu_328_p2(0) = '1') else 
        p_Result_2_0_i_i_fu_389_p3;
    axi_last_V_fu_356_p2 <= "1" when (j_i_i_reg_270 = tmp_13_i_i_reg_534) else "0";
    exitcond1_i_i_fu_334_p2 <= "1" when (i_i_i_reg_259 = tmp_i_i_reg_524) else "0";
    exitcond_i_fu_345_p2 <= "1" when (j_i_i_reg_270 = tmp_12_cast_i_i_reg_529) else "0";
    grp_reg_unsigned_short_s_fu_289_ap_start <= ap_reg_grp_reg_unsigned_short_s_fu_289_ap_start;
    grp_reg_unsigned_short_s_fu_289_in_r <= HwReg_height(12 - 1 downto 0);
    grp_reg_unsigned_short_s_fu_295_ap_start <= ap_reg_grp_reg_unsigned_short_s_fu_295_ap_start;
    grp_reg_unsigned_short_s_fu_295_in_r <= HwReg_width(12 - 1 downto 0);
    i_fu_339_p2 <= std_logic_vector(unsigned(i_i_i_reg_259) + unsigned(ap_const_lv12_1));
    j_fu_350_p2 <= std_logic_vector(unsigned(j_i_i_reg_270) + unsigned(ap_const_lv11_1));
    m_axis_video_TDATA <= m_axis_video_V_data_V_1_data_out;

    m_axis_video_TDATA_blk_n_assign_proc : process(m_axis_video_V_data_V_1_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_i_reg_566, ap_enable_reg_pp0_iter2, ap_reg_pp0_iter1_exitcond_i_reg_566)
    begin
        if ((((ap_const_lv1_0 = ap_reg_pp0_iter1_exitcond_i_reg_566) and (ap_block_pp0_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2)) or ((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            m_axis_video_TDATA_blk_n <= m_axis_video_V_data_V_1_state(1);
        else 
            m_axis_video_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m_axis_video_TDEST <= m_axis_video_V_dest_V_1_data_out;
    m_axis_video_TID <= m_axis_video_V_id_V_1_data_out;
    m_axis_video_TKEEP <= m_axis_video_V_keep_V_1_data_out;
    m_axis_video_TLAST <= m_axis_video_V_last_V_1_data_out;
    m_axis_video_TSTRB <= m_axis_video_V_strb_V_1_data_out;
    m_axis_video_TUSER <= m_axis_video_V_user_V_1_data_out;
    m_axis_video_TVALID <= m_axis_video_V_dest_V_1_state(0);
    m_axis_video_V_data_V_1_ack_in <= m_axis_video_V_data_V_1_state(1);
    m_axis_video_V_data_V_1_ack_out <= m_axis_video_TREADY;

    m_axis_video_V_data_V_1_data_out_assign_proc : process(m_axis_video_V_data_V_1_payload_A, m_axis_video_V_data_V_1_payload_B, m_axis_video_V_data_V_1_sel)
    begin
        if ((ap_const_logic_1 = m_axis_video_V_data_V_1_sel)) then 
            m_axis_video_V_data_V_1_data_out <= m_axis_video_V_data_V_1_payload_B;
        else 
            m_axis_video_V_data_V_1_data_out <= m_axis_video_V_data_V_1_payload_A;
        end if; 
    end process;

    m_axis_video_V_data_V_1_load_A <= (m_axis_video_V_data_V_1_state_cmp_full and not(m_axis_video_V_data_V_1_sel_wr));
    m_axis_video_V_data_V_1_load_B <= (m_axis_video_V_data_V_1_state_cmp_full and m_axis_video_V_data_V_1_sel_wr);
    m_axis_video_V_data_V_1_sel <= m_axis_video_V_data_V_1_sel_rd;
    m_axis_video_V_data_V_1_state_cmp_full <= '0' when (m_axis_video_V_data_V_1_state = ap_const_lv2_1) else '1';

    m_axis_video_V_data_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_reg_566, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_video_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_video_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_video_V_data_V_1_vld_out <= m_axis_video_V_data_V_1_state(0);
    m_axis_video_V_dest_V_1_ack_in <= m_axis_video_V_dest_V_1_state(1);
    m_axis_video_V_dest_V_1_ack_out <= m_axis_video_TREADY;
    m_axis_video_V_dest_V_1_data_out <= ap_const_lv1_0;
    m_axis_video_V_dest_V_1_sel <= m_axis_video_V_dest_V_1_sel_rd;

    m_axis_video_V_dest_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_reg_566, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_video_V_dest_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_video_V_dest_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_video_V_dest_V_1_vld_out <= m_axis_video_V_dest_V_1_state(0);
    m_axis_video_V_id_V_1_ack_in <= m_axis_video_V_id_V_1_state(1);
    m_axis_video_V_id_V_1_ack_out <= m_axis_video_TREADY;
    m_axis_video_V_id_V_1_data_out <= ap_const_lv1_0;
    m_axis_video_V_id_V_1_sel <= m_axis_video_V_id_V_1_sel_rd;

    m_axis_video_V_id_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_reg_566, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_video_V_id_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_video_V_id_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_video_V_id_V_1_vld_out <= m_axis_video_V_id_V_1_state(0);
    m_axis_video_V_keep_V_1_ack_in <= m_axis_video_V_keep_V_1_state(1);
    m_axis_video_V_keep_V_1_ack_out <= m_axis_video_TREADY;
    m_axis_video_V_keep_V_1_data_out <= ap_const_lv6_3F;
    m_axis_video_V_keep_V_1_sel <= m_axis_video_V_keep_V_1_sel_rd;

    m_axis_video_V_keep_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_reg_566, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_video_V_keep_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_video_V_keep_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_video_V_keep_V_1_vld_out <= m_axis_video_V_keep_V_1_state(0);
    m_axis_video_V_last_V_1_ack_in <= m_axis_video_V_last_V_1_state(1);
    m_axis_video_V_last_V_1_ack_out <= m_axis_video_TREADY;

    m_axis_video_V_last_V_1_data_out_assign_proc : process(m_axis_video_V_last_V_1_payload_A, m_axis_video_V_last_V_1_payload_B, m_axis_video_V_last_V_1_sel)
    begin
        if ((ap_const_logic_1 = m_axis_video_V_last_V_1_sel)) then 
            m_axis_video_V_last_V_1_data_out <= m_axis_video_V_last_V_1_payload_B;
        else 
            m_axis_video_V_last_V_1_data_out <= m_axis_video_V_last_V_1_payload_A;
        end if; 
    end process;

    m_axis_video_V_last_V_1_load_A <= (m_axis_video_V_last_V_1_state_cmp_full and not(m_axis_video_V_last_V_1_sel_wr));
    m_axis_video_V_last_V_1_load_B <= (m_axis_video_V_last_V_1_state_cmp_full and m_axis_video_V_last_V_1_sel_wr);
    m_axis_video_V_last_V_1_sel <= m_axis_video_V_last_V_1_sel_rd;
    m_axis_video_V_last_V_1_state_cmp_full <= '0' when (m_axis_video_V_last_V_1_state = ap_const_lv2_1) else '1';

    m_axis_video_V_last_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_reg_566, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_video_V_last_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_video_V_last_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_video_V_last_V_1_vld_out <= m_axis_video_V_last_V_1_state(0);
    m_axis_video_V_strb_V_1_ack_in <= m_axis_video_V_strb_V_1_state(1);
    m_axis_video_V_strb_V_1_ack_out <= m_axis_video_TREADY;
    m_axis_video_V_strb_V_1_data_out <= ap_const_lv6_0;
    m_axis_video_V_strb_V_1_sel <= m_axis_video_V_strb_V_1_sel_rd;

    m_axis_video_V_strb_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_reg_566, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_video_V_strb_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_video_V_strb_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_video_V_strb_V_1_vld_out <= m_axis_video_V_strb_V_1_state(0);
    m_axis_video_V_user_V_1_ack_in <= m_axis_video_V_user_V_1_state(1);
    m_axis_video_V_user_V_1_ack_out <= m_axis_video_TREADY;

    m_axis_video_V_user_V_1_data_out_assign_proc : process(m_axis_video_V_user_V_1_payload_A, m_axis_video_V_user_V_1_payload_B, m_axis_video_V_user_V_1_sel)
    begin
        if ((ap_const_logic_1 = m_axis_video_V_user_V_1_sel)) then 
            m_axis_video_V_user_V_1_data_out <= m_axis_video_V_user_V_1_payload_B;
        else 
            m_axis_video_V_user_V_1_data_out <= m_axis_video_V_user_V_1_payload_A;
        end if; 
    end process;

    m_axis_video_V_user_V_1_load_A <= (m_axis_video_V_user_V_1_state_cmp_full and not(m_axis_video_V_user_V_1_sel_wr));
    m_axis_video_V_user_V_1_load_B <= (m_axis_video_V_user_V_1_state_cmp_full and m_axis_video_V_user_V_1_sel_wr);
    m_axis_video_V_user_V_1_sel <= m_axis_video_V_user_V_1_sel_rd;
    m_axis_video_V_user_V_1_state_cmp_full <= '0' when (m_axis_video_V_user_V_1_state = ap_const_lv2_1) else '1';

    m_axis_video_V_user_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_reg_566, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_video_V_user_V_1_vld_in <= ap_const_logic_1;
        else 
            m_axis_video_V_user_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_video_V_user_V_1_vld_out <= m_axis_video_V_user_V_1_state(0);
    p_Result_0_i_i_fu_397_p3 <= (ap_const_lv40_FFFFFFFFFF & stream_csc_V_val_1_s_dout);
    p_Result_2_0_i_i_fu_389_p3 <= (ap_const_lv40_FFFFFFFFFF & stream_csc_V_val_0_s_dout);
    sel_tmp2_i_fu_328_p2 <= "1" when (HwReg_OutVideoFormat = ap_const_lv8_0) else "0";
    sel_tmp_i_fu_322_p2 <= "1" when (HwReg_OutVideoFormat = ap_const_lv8_1) else "0";
    stream_csc_V_val_0_s0_status <= (stream_csc_V_val_5_s_empty_n and stream_csc_V_val_4_s_empty_n and stream_csc_V_val_3_s_empty_n and stream_csc_V_val_2_s_empty_n and stream_csc_V_val_1_s_empty_n and stream_csc_V_val_0_s_empty_n);

    stream_csc_V_val_0_s0_update_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_reg_566, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0_11001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_csc_V_val_0_s0_update <= ap_const_logic_1;
        else 
            stream_csc_V_val_0_s0_update <= ap_const_logic_0;
        end if; 
    end process;


    stream_csc_V_val_0_s_blk_n_assign_proc : process(stream_csc_V_val_0_s_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_i_reg_566)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_csc_V_val_0_s_blk_n <= stream_csc_V_val_0_s_empty_n;
        else 
            stream_csc_V_val_0_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_csc_V_val_0_s_read <= stream_csc_V_val_0_s0_update;

    stream_csc_V_val_1_s_blk_n_assign_proc : process(stream_csc_V_val_1_s_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_i_reg_566)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_csc_V_val_1_s_blk_n <= stream_csc_V_val_1_s_empty_n;
        else 
            stream_csc_V_val_1_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_csc_V_val_1_s_read <= stream_csc_V_val_0_s0_update;

    stream_csc_V_val_2_s_blk_n_assign_proc : process(stream_csc_V_val_2_s_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_i_reg_566)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_csc_V_val_2_s_blk_n <= stream_csc_V_val_2_s_empty_n;
        else 
            stream_csc_V_val_2_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_csc_V_val_2_s_read <= stream_csc_V_val_0_s0_update;

    stream_csc_V_val_3_s_blk_n_assign_proc : process(stream_csc_V_val_3_s_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_i_reg_566)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_csc_V_val_3_s_blk_n <= stream_csc_V_val_3_s_empty_n;
        else 
            stream_csc_V_val_3_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_csc_V_val_3_s_read <= stream_csc_V_val_0_s0_update;

    stream_csc_V_val_4_s_blk_n_assign_proc : process(stream_csc_V_val_4_s_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_i_reg_566)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_csc_V_val_4_s_blk_n <= stream_csc_V_val_4_s_empty_n;
        else 
            stream_csc_V_val_4_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_csc_V_val_4_s_read <= stream_csc_V_val_0_s0_update;

    stream_csc_V_val_5_s_blk_n_assign_proc : process(stream_csc_V_val_5_s_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, exitcond_i_reg_566)
    begin
        if (((ap_const_lv1_0 = exitcond_i_reg_566) and (ap_block_pp0_stage0 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            stream_csc_V_val_5_s_blk_n <= stream_csc_V_val_5_s_empty_n;
        else 
            stream_csc_V_val_5_s_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    stream_csc_V_val_5_s_read <= stream_csc_V_val_0_s0_update;
    tmp_12_cast_i_i_fu_306_p4 <= grp_reg_unsigned_short_s_fu_295_ap_return(11 downto 1);
    tmp_13_i_i_fu_316_p2 <= std_logic_vector(signed(ap_const_lv11_7FF) + signed(tmp_12_cast_i_i_fu_306_p4));
    tmp_2_i_fu_426_p3 <= 
        stream_csc_V_val_0_s_dout when (sel_tmp2_i_fu_328_p2(0) = '1') else 
        tmp_i_73_fu_419_p3;
    tmp_3_i_fu_433_p3 <= 
        stream_csc_V_val_3_s_dout when (sel_tmp_i_fu_322_p2(0) = '1') else 
        stream_csc_V_val_4_s_dout;
    tmp_4_i_fu_440_p3 <= 
        stream_csc_V_val_4_s_dout when (sel_tmp2_i_fu_328_p2(0) = '1') else 
        tmp_3_i_fu_433_p3;
    tmp_5_i_fu_447_p3 <= 
        stream_csc_V_val_4_s_dout when (sel_tmp_i_fu_322_p2(0) = '1') else 
        stream_csc_V_val_5_s_dout;
    tmp_6_i_fu_454_p3 <= 
        stream_csc_V_val_5_s_dout when (sel_tmp2_i_fu_328_p2(0) = '1') else 
        tmp_5_i_fu_447_p3;
    tmp_7_i_fu_461_p3 <= 
        stream_csc_V_val_5_s_dout when (sel_tmp_i_fu_322_p2(0) = '1') else 
        stream_csc_V_val_2_s_dout;
    tmp_8_i_fu_468_p3 <= 
        stream_csc_V_val_3_s_dout when (sel_tmp2_i_fu_328_p2(0) = '1') else 
        tmp_7_i_fu_461_p3;
    tmp_9_i_fu_475_p6 <= ((((tmp_8_i_fu_468_p3 & tmp_6_i_fu_454_p3) & tmp_4_i_fu_440_p3) & tmp_2_i_fu_426_p3) & tmp_i_fu_412_p3);
    tmp_data_V_fu_489_p5 <= (tmp_9_i_fu_475_p6 & axi_0_2_0_i_i_fu_405_p3(7 downto 0));
    tmp_i_73_fu_419_p3 <= 
        stream_csc_V_val_2_s_dout when (sel_tmp_i_fu_322_p2(0) = '1') else 
        stream_csc_V_val_3_s_dout;
    tmp_i_fu_412_p3 <= 
        stream_csc_V_val_2_s_dout when (sel_tmp2_i_fu_328_p2(0) = '1') else 
        stream_csc_V_val_1_s_dout;
end behav;
